name: 'vandyhacks'
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v2.3.1
    - uses: cachix/install-nix-action@v14.1
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v10
      with:
        name: vandyhacks
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: "Build witness"
      run: nix --experimental-features 'nix-command flakes' build
